language: node_js
node_js: stable
branches:
  only:
  - main
before_install:
- npm install -g hexo-cli
install:
- npm install
- npm install hexo-deployer-git --save
script:
  - hexo clean
  - hexo generate
after_script:
  - git config user.name "黄荣君"
  - git config user.email "l1091462907@gmail.com"
  # 替换同目录下的_config.yml文件中gh_token字符串为travis后台刚才配置的变量，注意此处sed命令用了双引号。单引号无效！
  - sed -i "s/gh_token/${GH_TOKEN}/g" ./_config.yml
  - hexo deploy