language: node_js
node_js: stable
branches:
  only:
  - develop
before_install:
- npm install -g hexo-cli
install:
- npm install
script:
- git submodule init
- git submodule update
- hexo clean
- hexo g
after_success:
- git config --global user.name "黄荣君"
- git config --global user.email "l1091462907@gmail.com"
- sed -i'' "s~git@github.com:HuangRongjun/HuangRongjun.github.io.git~https://${GH_TOKEN}:x-oauth-basic@github.com/HuangRongjun/HuangRongjun.github.io.git~" _config.yml
- hexo d
env:
  global:
    secure: daHNH/MrYSBBgUAE5FYoACX+0t/AoMePdu4/rFgO1Z4eELsHAPbrC+T+zc9CDCzQDx9Mlce6GUHXyz6lKt+p2RxRudWZYmJ6OhWabVLhgMRujhOPVyA9J+p+jzV0llzJr6q6m9nbBCwUbzLID8uOez28M+b3jZ3WOttKVb7cK77dM1pVgZbmOixgivxj/z20fMsf/g3jOt0tGhXHP0l87r6CorM6sJ8U6kgNEoYd4VQJiCMtAyB1X7SqJzJN+gDBLzU+KCysPp8I1pUoezSmnrn26CFOYPkaGytUUyO/oNaeclQ9QuRTnDC1Wk+WB4aO5M9XVlRklgf2xesBCOKLvxbvE7pplkSdsjEI1BTWWRfl+SiYFlXD3lIUYHoDPXTL91rnRR5O4Cut7U6avfvx+06Vv1rE0zAPX4RzlYZq1YCKWwOE1fEdiY56q5u5ZwLohWCKRLeu5ojDqi74vob2E0CLo49+ZmiD1gHo1x+GA4iUsUnRx0qqhfz0OeeM/LF3hFVsIlqsLKLE7RFLbjLxZIP7xxoFmDhz1P2mbeMGJvxkT6Z2vOBt4DsRKaXfZKuyXx0BmSUId9g2gfO0UZxlYlNie7mXr/uLFH4y6zJbatinatc8lFAgbtNp4KbTkNUyiOsg4Q7U6PL7JieSI8ZXZvTsbBmzoAWZqolAo7u2C6A=
