language: node_js
node_js: stable

install:
  - npm install

script:
  - hexo g

after_script:
  - cd ./public
  - git init
  - git config user.name "黄荣君"
  - git config user.email "l1091462907@gmail.com"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master
  - hexo d

branches:
  only:
    - master
env:
 global:
   - GH_REF: https://github.com/iCrazyTeam/iCrazyTeam.github.io.git