language: node_js
node_js: stable
branches:
  only:
  - master
before_install:
- npm install -g hexo-cli
install:
- npm install
script:
- git submodule init
- git submodule update
- hexo clean
- hexo g
after_success:
- git config --global user.name "黄荣君"
- git config --global user.email "l1091462907@gmail.com"
- sed -i'' "s~git@github.com:itjun/itjun.github.io.git~https://${GH_TOKEN}:x-oauth-basic@github.com/itjun/itjun.github.io.git~" _config.yml
- hexo d
env:
  global:
    secure: nIdtXUhP6bgMFFLK68WJVv7fxKh7TBokfMoN7fS6p33gCrbDTmaYulpQP3EAzIsErZN5xVrqLe6eh1ClFAVMVnJIIMmRmVTWB2D+5qOidrFJU4YcZD9aXoCokAsWSqDPeYsBFwUrG1Cb1+6PQwCzGPulrBMwGrBF+wqj+JyO4G1pBX7m9mHrVqJ3c3CW9hfmAKa/UwxjPdCdTDpEHufaaC/Vsbir+6XRF9ZZ1EIPbRMz29cJn6/vZDQbDJPQXlJwLmpUHXDa6kVMX7q/xZ1eNi1X8qN4/lFutC/ZSyQpmtmACOGpL1zAX/s672U0kCfT8HSCLgFUE6eB9/Lq4sDKG5Bl+D2uo9SYUAiF6JDkWasvqEOLOdiequOOzj28CuNwz/bMzO8KKaoiGm2WriOu9GVnc0HOMs2h4Kz1Ifg+NGBjeZkSWwu1onUmxAVxp0On7z5FcuucE+cSAMV3YUYJuzAYDTK5+jVf4w1JjB9K0iwPO0v04rnhnn1FYDd9HCk1tpL3fWb4nSLofTi43Os8T1W4Mz+KNBYjckygIkUK2lEX1ljmlrngRPLjPtj08Gxsv2W2nO0MHfxWLHjHIYiRXMmA70h2Kcg0sgPQn5zKO9PhcGITnzBFCH3eYXmPSIcsgCwIBpoWVyArRZU3QdfJdgwI6k0rq8dmqB5oUptlRKE=
