language: node_js
node_js: stable
branches:
  only:
  - master
before_install:
- npm install -g hexo-cli
install:
- npm install
script:
- git submodule init
- git submodule update
- hexo clean
- hexo g
after_success:
- git config --global user.name "黄荣君"
- git config --global user.email "l1091462907@gmail.com"
- sed -i'' "s~git@github.com:HuangRongjun/HuangRongjun.github.io.git~https://${GH_TOKEN}:x-oauth-basic@github.com/HuangRongjun/HuangRongjun.github.io.git~" _config.yml
- hexo d
env:
  global:
    secure: qgHF435WKYhB5PZE+Tcp7Y1Y48P/C/z/iGBYtLUpzOrh6547qmImkmL2X1UowghJTDHGoSCdxupQqEai625NXOLFXPF5rAxewZesLL2WpRYsLtc6G2mT1VC2UxRXuHTkXXlz8GNeimo2VDOXy+ALvB3pKAoJERg2UY9086r/+rCKLj8YIQ9ER/Os//1Ue/SrUWeWYa7sXmLCVNvNYQpVM+yvAlaoGwgMwPV6vLbkbZt/8g6vF72ZR11jP+5tNvPuehhRyJN7ts/j+ziOuMF4k6Jwbg8oOfacE9EoiAw2C4aKgjXTVZaTSmJ7/s0mFwjIVu2CQOl875HBW6fN+YRws8fnk2YvMyWT0HL8H31blJDZvvzEPBbvewzf5xRjnyxgZpvbiBfyEN1GY2L5jpO4TutJK5zpix/sK+TPGfVtHwp1NZPihCQeGvIZkZjbIEuWXEvRrb2HCCBa4PB5z8RZzvavl/zYTP3XDj120vJRlTPJUwS1R7LrUqPVHyF3JgnOn3+JwcLvfjyupuqOXtf99TFXiB3xHKxIJaSlDX3zZM4uzxo2ljzh33vJmIjDIrGHNSD4ZDHvuAktWCqy9AREIpJipghv3igKCG1wbfUbAEMxLEQWT3sGJlgFdYIUB0BR4WDn+N+D8j0HaYJ3aGUp15gk5zA0R1ORH7c+oSaQWJU=
